In [1]:
import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, 45, 56, np.nan],
'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
mv = df.isnull()
print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [5]:
import pandas as pd

data = {
    "ID": [1, 2, 3, 4],
    "Name": ["John", "Emma", "Liam", "Olivia"],
    "Gender": ["Male", None, "Male", None]
}

df = pd.DataFrame(data)
df.to_csv("sample.csv", index=False)

In [4]:
import pandas as pd

d = pd.read_csv("/content/sample.csv")
bool_series = pd.isnull(d["Gender"])
missing_gender_data = d[bool_series]
print(missing_gender_data)

   ID    Name Gender
1   2    Emma    NaN
3   4  Olivia    NaN

In [6]:
import pandas as pd
import numpy as np
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
'Age': [25, np.nan, 22, 28]}
df = pd.DataFrame(data)
# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [7]:
import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, 45, 56, np.nan],
'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
nmv = df.notnull()
print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [8]:
import pandas as pd
d = pd.read_csv("/content/sample.csv")
nmg = pd.notnull(d["Gender"])
nmgd= d[nmg]
display(nmgd)

   ID  Name Gender
0   1  John   Male
2   3  Liam   Male

In [9]:
import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, 45, 56, np.nan],
'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [10]:
import pandas as pd
import numpy as np
d = pd.read_csv("/content/sample.csv")
d[10:25]

Empty DataFrame
Columns: [ID, Name, Gender]
Index: []

In [11]:
import pandas as pd
import numpy as np
dict = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, np.nan, 45, 56],
'Third Score': [52, 40, 80, 98],
'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [12]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna(how='all')

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

In [13]:
import pandas as pd
d = pd.read_csv("/content/sample.csv")
nd = d.dropna(axis=0, how='any')
print("Old data frame length:", len(d))
print("New data frame length:", len(nd))
print("Rows with at least one missing value:", (len(d) - len(nd)))

Old data frame length: 4
New data frame length: 2
Rows with at least one missing value: 2